modLoader="javafml"
loaderVersion="[40,)"
license="ARR"

[[mods]]
modId="fruittrees"
version="${file.jarVersion}"
displayName="Fruit Trees"
authors="Snownee, WZD, MalayP, minzhi"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fruit-trees"
description=""

[[dependencies.fruittrees]]
    modId="kiwi"
    mandatory=true
    versionRange="[6, 7)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fruittrees]]
    modId="forge"
    mandatory=true
    versionRange="[40, )"
    ordering="NONE"
    side="BOTH"

[modproperties.fruittrees]
    catalogueItemIcon="fruittrees:grapefruit"
    farmersdelightCabinetCompat=[ "fruittrees:citrus_cabinet", "fruittrees:cherry_cabinet" ]
