modLoader="javafml"
loaderVersion="[38,)"
license="ARR"

[[mods]]
modId="fruittrees"
version="${file.jarVersion}"
displayName="Fruit Trees"
authors="Snownee, WZD, MalayP, minzhi"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fruit-trees"
description=""

[[dependencies.fruittrees]]
    modId="kiwi"
    mandatory=true
    versionRange="[5.1, 6)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.fruittrees]]
    modId="forge"
    mandatory=true
    versionRange="[38, )"
    ordering="BEFORE"
    side="BOTH"

[modproperties.fruittrees]
    catalogueItemIcon="fruittrees:grapefruit"
    farmersdelightPantryCompat=[ "fruittrees:citrus_pantry", "fruittrees:cherry_pantry" ]
