modLoader="javafml"
loaderVersion="[44,)"
license="ARR"

[[mods]]
modId="fruittrees"
version="${file.jarVersion}"
displayName="Fruit Trees"
authors="Snownee, WZD, MalayP, minzhi"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fruit-trees"
description=""

[[dependencies.fruittrees]]
    modId="kiwi"
    mandatory=true
    versionRange="[9.1, 10)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fruittrees]]
    modId="forge"
    mandatory=true
    versionRange="[44, )"
    ordering="NONE"
    side="BOTH"

[modproperties.fruittrees]
    catalogueItemIcon="fruittrees:grapefruit"
